//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBExamen3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneo
    {
        public int idTorneos { get; set; }
        public int idAdministradorITM { get; set; }
        public string TipoTorneo { get; set; }
        public string NombreTorneo { get; set; }
        public string NombreEquipo { get; set; }
        public int ValorInscripcion { get; set; }
        public System.DateTime FechaTorneo { get; set; }
        public string Integrantes { get; set; }
    
        public virtual AdministradorITM AdministradorITM { get; set; }
    }
}
